### ISSUE TITLE
Find mutual from the overall ranking

### ISSUE THREAD

**Issue by hayasaka-san-kr** [sibyl666/osu-mutual-finder#8]
Hi, 

1) Can you make a function to find the mutual from the overall ranking?(Not a country ranking)

2) Can you make a function to save players who are checked and ignore them in the next finding?

3) My BN and GMT friends reported that they are stucked on email verification(wrong code), do you know why?

**Comment by sibyl666** [comment]
1. I can make it so that the program start will from the first id (1) and then checks everyone by incrementing the number but I don't think this is a good solution. There are a bunch of dead ids between numbers.

2. Actually this is a good idea, I can put a setting that will put numbers in the blacklist automatically. In the meantime, you can keep track of the page that the program left on and then use it to keep it from starting from 0.

3. I know about this issue but cause I don't have access to GMT account I don't know what is the problem. Probably with accounts that have extra perms there is extra verification stuff going on in the background.

**Comment by hayasaka-san-kr** [comment]
1) I mean, can you make the program add friends starting from the #1 in the global ranking (Like sakamata1, aetrna, lifeline...)

**Comment by sibyl666** [comment]
Yeah, I can add this soon.

**Comment by sibyl666** [comment]
Released with https://github.com/sibyl666/osu-mutual-finder/releases/tag/v1.2.9
